name: Maven CI-CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Verify Tools
        run: |
          java -version
          mvn -version
          docker --version
          

      - name: Build Application
        run: mvn clean compile

  unit-test:
    needs: build
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: mvn test

  integration-test:
    needs: build
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Run Integration Tests
        run: mvn verify



  docker-build:
    needs:
      - unit-test
      - integration-test


    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.run_number }} .

  ecr-push:
    needs: docker-build

    runs-on: [self-hosted, Windows, X64, malab]

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: 123456789012
      ECR_REPO: myapp

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        shell: powershell
        run: |
          aws ecr get-login-password --region $env:AWS_REGION |
          docker login --username AWS --password-stdin "$env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com"

      - name: Tag Image
        run: |
          docker tag myapp:${{ github.run_number }} `
          $env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPO:${{ github.run_number }}

      - name: Push Image
        run: |
          docker push `
          $env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPO:${{ github.run_number }}

  deploy-ecs:
    needs: ecr-push

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Deploy ECS Service
        run: |
          aws ecs update-service ^
          --cluster my-cluster ^
          --service my-service ^
          --force-new-deployment

  notify:
    if: failure()

    needs:
      - build
      - unit-test
      - integration-test
      - security-scan
      - docker-build
      - ecr-push
      - deploy-ecs

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Pipeline Failed
        run: |
          echo Pipeline Failed
          echo Triggered by ${{ github.actor }}
