name: Maven CI-CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "123456789012"
  ECR_REPO: myapp
  ECS_CLUSTER: my-cluster
  ECS_SERVICE: my-service
  IMAGE_TAG: ${{ github.run_number }}

jobs:

  build:
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Verify Tools
        shell: powershell
        run: |
          java -version
          mvn -version
          docker --version
         

      - name: Build Application
        shell: powershell
        run: |
          mvn clean package -DskipTests

  unit-test:
    needs: build
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        shell: powershell
        run: |
          mvn test

  integration-test:
    needs: unit-test
    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Run Integration Tests
        shell: powershell
        run: |
          mvn verify

  docker-build:
    needs:
      - integration-test

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        shell: powershell
        run: |
          docker build -t myapp:${{ env.IMAGE_TAG }} .

  ecr-push:
    needs: docker-build

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Access
        shell: powershell
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image
        shell: powershell
        run: |
          docker tag myapp:${{ env.IMAGE_TAG }} `
          $env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPO:${{ env.IMAGE_TAG }}

      - name: Push Docker Image
        shell: powershell
        run: |
          docker push `
          $env:AWS_ACCOUNT_ID.dkr.ecr.$env:AWS_REGION.amazonaws.com/$env:ECR_REPO:${{ env.IMAGE_TAG }}

  deploy-ecs:
    needs: ecr-push

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy ECS Service
        shell: powershell
        run: |
          aws ecs update-service `
            --cluster $env:ECS_CLUSTER `
            --service $env:ECS_SERVICE `
            --force-new-deployment

  notify:
    if: failure()

    needs:
      - build
      - unit-test
      - integration-test
      - docker-build
      - ecr-push
      - deploy-ecs

    runs-on: [self-hosted, Windows, X64, malab]

    steps:
      - name: Pipeline Failed
        shell: powershell
        run: |
          Write-Host "Pipeline Failed"
          Write-Host "Triggered by: ${{ github.actor }}"
