name: my MANUAL

on:
 push:
  branches: 
    - main
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
     - name: checkout git
       uses: actions/checkout@v4

     - name: print msg
       run: echo "hello world"
